---
title: "Poplar Lawn maps"
date: today
format:
  html:
    theme: flatly
    author: "Jonathan Knopf (jonathan@hdadvisors.net)"
execute: 
  echo: true
  warning: false
  freeze: auto
code-fold: true
code-overflow: scroll
editor: visual
---

## Setup

Load libraries and read in parcel shapefile

```{r}
#| label: setup

library(tidyverse)
library(sf)
library(mapview)

# Read in shapefile and drop Z dimension
pl_shp <- st_read("data/PoplarLawn2023.shp", quiet = TRUE) |>
  st_zm()

# Create residential/non-residential and owner/renter-occupied fields

pl_parcels <- pl_shp |> 
  mutate(residential = case_when(
    str_detect(State_Cl_1, "Family") ~ "Residential",
    TRUE ~ "Non-residential"
  )) |> 
  mutate(tenure = case_when(
    residential == "Residential" & Street_Nam == Owner_Mail ~ "Owner-occupied",
    residential == "Residential" & Street_Nam != Owner_Mail ~ "Renter-occupied",
    TRUE ~ "Non-residential"
  ))

# Export as csv
# write_csv(pl_shp, "poplar-lawn-shp.csv")
  
```

## Maps

### Residential and non-residential parcels

```{r}
#| label: residential

mapview(
  pl_parcels,
  layer.name = "Parcel use",
  zcol = "residential",
  popup = "Street_Nam"
  )

```

### Housing tenure of residential parcels

```{r}
#| label: tenure

mapview(
  pl_parcels,
  layer.name = "Tenure",
  zcol = "tenure",
  popup = "Street_Nam",
  col.regions = c("ivory3", "cyan4", "darkgoldenrod2")
  )

```
