project: 
  type: book
  execute-dir: file
  output-dir: docs

execute:
  freeze: auto

book:
  title: "Quarto Test"
  author:
    - name: Jonathan Knopf
      affiliations:
        - HDAdvisors
  downloads: pdf
  date: today
  chapters:
    - index.qmd
    - part: "Part 1: Plots"
      chapters:
        - ggplot.qmd
        - ggiraph.qmd
        - plotly.qmd
    - part: "Part 2: Maps"
      chapters:
        - leaflet.qmd
        - mapview.qmd
  # appendices:
  #   - references.qmd

knitr:
  opts_chunk: 
    echo: true
    warning: false
    message: false
    crop: false

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt