# Leaflet

This page is a demonstration of an interactive Leaflet map rendered in Quarto.

```{r}
#| label: fig-leaflet
#| fig-cap: "Federally assisted rental properties in Chesterfield County"

library(tidyverse)
library(janitor)
library(leaflet)

nhpd <- read_csv("data/nhpd_chesterfield.csv") |> 
  clean_names() |> 
  filter(subsidy_status != "Inactive")

pal <- colorFactor(palette = c("blue", "red", "green", "orange"),
                   levels = c("LIHTC", "Section 8", "HUD Insured",
                              "Section 202 or Section 236"))

leaflet(nhpd) |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(
    lng = ~long,
    lat = ~lat,
    radius = 4,
    color = ~pal(subsidy),
    stroke = FALSE, fillOpacity = 0.5
    ) |> 
  addLegend("bottomright", pal = pal, values = ~subsidy,
            title = "Federal program", opacity = 1)

```

```{r}
#| label: fig-ash-map
#| fig-cap: "Map of Town of Ashland"

library(sf)

ashland <- st_read('https://services2.arcgis.com/sKZWgJlU6SekCzQV/arcgis/rest/services/Ashland_Boundary/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson', quiet = TRUE)

leaflet(ashland) %>% 
  addTiles() %>% 
  addPolygons()

```
