---
title: "Virginia Housing Trust Fund"
subtitle: "FY2014 - FY2025"
format:
  html:
    theme: flatly
    author: "Jonathan Knopf (jonathan@hdadvisors.net)"
execute: 
  echo: false
  warning: false
  freeze: auto
---

Setup

```{r}
#| label: setup
#| output: false

source("vhtf.R")

#setwd("R:/sandbox/vha/vhtf")

vhtf_raw <- read_csv("data/vhtf-projects-all.csv")

vhtf_sum <- read_csv("data/vhtf-summary.csv") |> 
  mutate(year = str_replace_all(year, "FY20", "FY"))

```

Load districts

```{r}
#| label: districts
#| eval: false

senate <- st_read("gis/va_senate_2021.geojson", quiet = TRUE) |> 
  st_transform(4326)

senate$chamber <- "Senate"
senate$DISTRICT <- paste("SD", senate$DISTRICT)

house <- st_read("gis/va_house_2021.geojson", quiet = TRUE) |> 
  st_transform(4326)

house$chamber <- "House"
house$DISTRICT <- paste("HD", house$DISTRICT)

districts <- bind_rows(senate, house) |> 
  select(chamber, district = DISTRICT, n = DISTRICTN) |> 
  arrange(chamber, n)

# Calculate minimum and maximum x and y values for each feature
districts$min_x <- sapply(st_geometry(districts), function(geom) {
  st_bbox(geom)[1]
})
districts$max_x <- sapply(st_geometry(districts), function(geom) {
  st_bbox(geom)[3]
})
districts$min_y <- sapply(st_geometry(districts), function(geom) {
  st_bbox(geom)[2]
})
districts$max_y <- sapply(st_geometry(districts), function(geom) {
  st_bbox(geom)[4]
})

write_rds(districts, "data/districts.rds")

```

```{r}

library(tigris)

counties <- counties("va")

vaco <- counties |> 
  select(locality = NAMELSAD) |> 
  st_transform(4326)

```


Geocode VHTF projects

```{r}
#| label: geocode
#| eval: false

# Updated: 2024-12-16

library(sf)
library(tidygeocoder)

sf_use_s2(FALSE)

vhtf_geocode <- vhtf_raw |> 
  
  geocode(
    address = project_address,
    method = 'geocodio'
  ) |> 
  
  # Specify WGS 1984 coordinate system for lat/long data
  
  st_as_sf(coords = c("long", "lat"),
           remove = FALSE,
           crs = 4326) 

vhtf_geocode$popup <- paste(
  sep = "<br/>",
  paste0("<b>", vhtf_geocode$project_name, "</b>"),
  paste0("Award year: ", vhtf_geocode$year),
  paste0("Affordable units: ", vhtf_geocode$units_affordable),
  paste0("VHTF award: ", "$", formatC(as.numeric(vhtf_geocode$amt_vhtf), format = "f", digits = 0, big.mark = ","))
)

districts <- read_rds("data/districts.rds")

vhtf_districts <- vhtf_geocode |> 
  st_join(filter(select(districts, 1:2, 4), chamber == "House")) |> 
  st_join(filter(select(districts, 1:2, 4), chamber == "Senate")) |> 
  st_join(vaco) |> 
  select(1:25, house = 27, senate = 29, 30)

write_rds(vhtf_districts, "data/vhtf-districts.rds")

```

Annual allocations

```{r}
#| label: allocations

# Updated: 2024-12-16

subtitle1 <- c(
  "Annual award totals for <span style='color:#0C4D4F'>**Loans**</span> and
  <span style='color:#A0D18E'>**Grants**</span>, plus 
  <span style='color:#ECC51E'>**Administrative Costs** </span> (FY2014 - FY2025)"
  )

# caption1 <- c(
#   "**Source:** Virginia Department of Housing and Community Development.\n
#   **Note:** The 2024-2026 Biennium Budget allocated $87.5 million to the VHTF in FY25. Awards have not yet been made."
#   )

caption1 <- c(
  "**Source:** Virginia Department of Housing and Community Development."
  )

allo_cols <- c(
  "Loans" = "#0C4D4F",
  "Grants" = "#A0D18E",
  "Admin" = "#ECC51E",
  "Budgeted" = "#0C4D4F"
)

allo_alpha <- c(
  "Loans" = 1,
  "Grants" = 1,
  "Admin" = 1,
  "Budgeted" = 0.75
)

vhtf_sum |> 
  filter(data %in% c("funding", "budget")) |> 
  ggplot(aes(year, value, fill = type, alpha = type)) +
  geom_col() +
  scale_fill_manual(values = allo_cols) +
  scale_alpha_manual(values = allo_alpha) +
  scale_y_continuous(
    breaks = c(0:8)*10000000,
    expand = c(0.01, 0),
    labels = label_dollar(accuracy = 1, scale = 0.000001, suffix = "MM")
    ) +
  add_zero_line() +
  labs(
    title = "How the Virginia Housing Trust Fund is used",
    subtitle = subtitle1,
    caption = caption1
  ) +
  theme_vha(base_size = 40) +
  theme(
    plot.caption = element_textbox_simple(
      size = 33,
      valign = 1,
      margin = ggplot2::margin(t = 10, unit = "pt")
      )
    )

ggsave("img/vhtf-annual-allocations.png", width = 8, height = 4.94, units = "in", bg = "white")

```

CLP units

```{r}
#| label: units

# Updated: 2024-12-16

vhtf_raw |> 
  summarise(
    n = n(),
    units = sum(units_affordable),
    funding = sum(amt_vhtf),
    .by = year
  ) |> 
  arrange(year) |> 
  mutate(units = cumsum(units)) |> 
  ggplot(aes(year, units, label = label_comma()(units))) +
  geom_col(fill = "#0C4D4F") +
  geom_text(
    size = 12,
    color = "#0C4D4F",
    vjust = -0.5
  ) +
  scale_y_continuous(
    limits = c(0, 22000),
    breaks = seq(5000, 20000, 5000),
    labels = label_comma(),
    expand = c(0.01, 0.05)
  ) +
  add_zero_line() +
  labs(
    title = "Affordable units produced by VHTF Competitive Loan Pool",
    subtitle = "Cumulative total of units affordable at 80% AMI or below (FY2014 - FY2024)",
    caption = "**Source:** Virginia Department of Housing and Community Development."
  ) +
  theme_vha(base_size = 40) +
  theme(
    axis.text.y = element_text(
      hjust = 0, vjust = -0.5,
      color = "grey70",
      size = 30,
      margin = margin(r = -32, unit = "pt")
    )
    #axis.text.y = element_blank()
  )

ggsave("img/vhtf-total-units.png", width = 8, height = 4.94, units = "in", bg = "white")

```

Total units by affordability and type

```{r}
#| label: units-type

vhtf_raw |> 
  summarise_at(
    vars(units_affordable:units_below80),
    sum,
    na.rm = TRUE
  ) |> 
  pivot_longer(
    everything(),
    names_to = "type",
    values_to = "units"
  ) |> 
  filter(type != "units_affordable") |> 
  mutate(
    type = case_match(
      type,
      "units_rehab" ~ "Rehabilitated",
      "units_psh" ~ "Permanent supportive housing",
      "units_below30" ~ "Affordable below 30% AMI",
      "units_below50" ~ "Affordable below 50% AMI",
      "units_below60" ~ "Affordable below 60% AMI",
      "units_below80" ~ "Affordable below 80% AMI"
    ),
    category = case_when(
      str_detect(type, "AMI") ~ "affordability",
      .default = "special"
    )
  ) |> 
  ggplot(aes(units, str_wrap(type, 14), fill = category, color = category, label = label_comma()(units))) +
  facet_grid(rows = vars(category), scales = "free_y", space = "free") +
  geom_col() +
  geom_text(
    size = 12,
    #color = "#0C4D4F",
    hjust = -0.3
  ) +
  scale_x_continuous(
    limits = c(0, 4000),
    expand = c(0.01, 0.05)
  ) +
  scale_fill_vha() +
  scale_color_vha() +
  add_zero_line("x") +
  labs(
    title = "Type of units produced by VHTF Competitive Loan Pool",
    subtitle = "Total number of units by affordability and type (FY2014 - FY2023)",
    caption = "**Source:** Virginia Department of Housing and Community Development.<br>**Note:** Unit totals are not mutually exclusive; for example, permanent supportive housing units are affordable at 30% AMI, and some are rehabilitated units."
  ) +
  theme_vha(base_size = 40) +
  theme(
    panel.grid.major.y = element_blank(),
    axis.text.x = element_blank(),
    strip.text = element_blank(),
    axis.text.y = element_text(
      lineheight = 0.3
    ),
    plot.caption = element_textbox_simple(
      lineheight = 0.4,
      margin = ggplot2::margin(t = 10)
    )
  )

library(ragg)

ggsave("vhtf-type-units.png", width = 8, height = 4.94, units = "in", bg = "white")

```

```{r}
#| label: demand

subtitle2 <- "Annual number of <span style='color:#A0D18E'>**applicants**</span> versus <span style='color:#0C4D4F'>**awards**</span> (FY2014 - FY2024)"

vhtf_sum |> 
  filter(
    data %in% c("applicants", "awardees"),
    year != "FY24"
    ) |> 
  summarise(
    n = sum(value),
    .by = c(year, type, data)
  ) |> 
  ggplot(aes(year, n, fill = data)) +
  facet_wrap(~type) +
  geom_col(position = "dodge") +
  scale_y_continuous(
    expand = c(0.01, 0.05)
  ) +
  scale_fill_vha(-1) +
  add_zero_line() +
  labs(
    title = "Demand for Virginia Housing Trust Fund funding",
    subtitle = subtitle2,
    caption = "**Source:** Virginia Department of Housing and Community Development.<br>**Note:** Incomplete data for total loan applicants and awards from FY2016 through FY2019."
  ) +
  theme_vha(base_size = 10) +
  theme(
    plot.caption = element_textbox_simple(
      lineheight = 0.4,
      margin = ggplot2::margin(t = 10)
    )
  )

ggsave("vhtf-demand.png", width = 8, height = 4.94, units = "in", bg = "white")

```

