
```{r}
#| label: setup

library(tidyverse)
library(scales)
library(showtext)

font_add_google(name = "Open Sans", family = "Open Sans")

showtext_auto()

nhpd <- read_csv("nhpd_va_subsidies_7_2022.csv") 

```

```{r}
#| label: data

nhpd_ph <- nhpd |> 
  filter(`Subsidy Name` == "Public Housing") |> 
  select(units = 10, name = 11, pha = 18, date = 26) |> 
  mutate(date = as.numeric(str_sub(date, start = 5L)))

nhpd_ph_group <- nhpd_ph |> 
  mutate(pha = str_to_title(pha)) |> 
  group_by(pha) |> 
  mutate(pha2 = case_when(
    sum(units) > 500 ~ pha,
    TRUE ~ "Other"
  )) |> 
  ungroup() |> 
  mutate(pha2 = str_remove(pha2, c(" Redevelopment & Housing Authority| Redevelopment & Housng Authority")),
         pha2 = fct_relevel(pha2, "Other", after = Inf))

```

```{r}
#| label: plot

ggplot(nhpd_ph_group,
       aes(x = date, y = units, fill = pha2)) +
  geom_col() +
  scale_fill_manual(values = c("#011e41", "#40c0c0", "#8b85ca", "#259591", "#b1005f", "#e0592a", "#9d9d9d")) +
  scale_x_continuous(limits = c(1938, 1991), breaks = c(1940, 1950, 1960, 1970, 1980, 1990)) +
  scale_y_continuous(labels = label_comma(), n.breaks = 8, expand = c(0,0)) +
  labs(title = "Public housing production in Virginia",
       subtitle = "1935 to 1990",
       x = "Year built",
       y = "Number of units",
       fill = "Public housing\nauthority",
       caption = "Source: National Housing Preservation Database.") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        panel.grid.major.y = element_line(color = "#dcdbdb"),
        axis.line.x = element_line(color = "#353535"),
        axis.ticks.x = element_line(),
        plot.caption = element_text(hjust = 0, color = "#696969"))

```



